version: '3'
services:
  php-apache:
    build: "./docker/php-apache"
    ports:
      - "80:80"
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: